### ISSUE TITLE
Fix usage example in README.md 

### ISSUE THREAD

**Issue by yaronius** [NicklasWallgren/bankid#7]
Hej Nicklas! 

Thank you for the nice library!

If you don't mind, I wanted to underpin my gratitude with a small contribution. Now the code example in README is not working, it needs to be updated to be runnable. Fixed it in https://github.com/NicklasWallgren/bankid/pull/6

**Comment by NicklasWallgren** [comment]
Hey @yaronius 

Thanks for the contribution. The `README.md` has been neglected and needs some tidying up. I have left some comments, and will be revisiting the PR shortly :)
